# Generated by Django 3.2.3 on 2021-08-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='files/product')),
                ('isfavorite', models.BooleanField(default=False)),
            ],
        ),
    ]
